server:
  port: 80
  tomcat:
    basedir: ../logs/${spring.application.name}/tomcat/

spring:
  application:
    name: gzh

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/assessment?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    password: wucena008

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.athub.dto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

gzhInfo:
  appId: wx384c16ccac5ef976
  appSecret: 3693f28bb82b0d0667510291b8409077